# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LosslessPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LosslessPlayer

  pod 'Masonry'
  pod 'ReactiveObjC'
  target 'LosslessPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LosslessPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
